### ISSUE TITLE
[Bug] !ping or !pingteam generates an exception

### ISSUE THREAD

**Issue by cboutet** [RouxRC/gazouilleur#15]
On #sequanux chan, using !ping or !pingteam command generates an exception http://pastebin.com/ydzRAnNB

**Comment by RouxRC** [comment]
It looks to me like this might be due to a problem in the config file.
Can you copy what the following lines say in `gazouilleur/config.py`:
`ADMINS = `
`GLOBAL_USERS = `

**Comment by simonguinot** [comment]
Here are the lines as defined in our configuration file:

```GLOBAL_USERS = ['cboutet', 'e1000', 'lolivz', 'sim'],```
```ADMINS = GLOBAL_USERS```

**Comment by RouxRC** [comment]
Thanks, can you repaste the exception, the pastebin expired and I can't recall what led me to thinking it could be this :)

**Comment by RouxRC** [comment]
Although, if there is indeed a comma at the end of the GLOBAL_USERS line, you should definitely remove it

**Comment by simonguinot** [comment]
Removing the comma fixes indeed the issue. Many thanks for your help !
