### ISSUE TITLE
Be able to connect to a channel that require a password

### ISSUE THREAD

**Issue by N3bTcx** [RouxRC/gazouilleur#21]
Hello

It would be awesome to be able to connect to irc channel that require password. 

Thanks a lot

**Comment by RouxRC** [comment]
Could you point me privately to a chan with a password that I could use for tests ?

**Comment by RouxRC** [comment]
if you pull and add the PASSWORD argument to your channel's config and restart you should be able to try now
see https://github.com/RouxRC/gazouilleur/commit/50cd5692387cc56a8aeef6bed30323e6cad40098#diff-e885a35f5c5ad2a18d8ade37049fb981R95

**Comment by N3bTcx** [comment]
Sorry @RouxRC didn't saw you're message. Thanks a lot. Will give a try.

**Comment by N3bTcx** [comment]
Works perfectly on a channel I created with `+k` option. Thanks
